### PR TITLE
Avoid use of private APIs from azure.storage

### PR DESCRIPTION
**Pull request by benrutter**
This is designed to fix [issue 426](https://github.com/fsspec/adlfs/issues/426), and remove use of private modules from azure.storage - hopefully help avoid future issues like the recent [sdk_moniker key error](https://github.com/fsspec/adlfs/issues/424) cropping in.

There's two changes here, both of which are pretty minor, but the second of which might need some discussion on whether it's the right approach.

## Import switches

```BlobPrefix```, ```BlobBlock```, ```BlobPoperties``` and ```BlobType ```are all exposed as importables straight from azure.storage.blob without needing the private modules, so this is a drop in replacement.

## Default Block Size

This change might need a little more discussion - I've hardcoded it here to avoid using ```create_configuration```, which @jalauzon-msft suggested as a possibility, but that means it won't automatically change if azure shifts it in future.

The alternative approaches I can think of are:
- Continue using ```create_configuration```, which would be responsive to changes from azure, but also potentially lead to issues in future since it is a private method.
- Open an issue with azure SDK to add default block size as a supported importable constant (and either leave as is or hardcode in the meantime)

### CODE REVIEW

**Comment by benrutter** [comment]
Looks like I did something unexpected since all the tests are now failing - not sure I understand where the errors are coming from though? (I've checked, and the new imports are definitely just extended ways of pulling from the initially private modules, so I don't think I've accidently switched out an azure object for another one)

**Comment by TomAugspurger** [comment]
Thanks @benrutter! Agreed with hardcoding the default block size and getting that from a public API if and when it's added to the azure SDK.

I wonder if the failing tests are fixed by https://github.com/fsspec/adlfs/pull/422. I'll take a closer look later in the week at these two PRs.

**Comment by TomAugspurger** [comment]
Hmm, seems that I can't push to your branch @benrutter. Are you able to merge main and update this PR?

**Comment by TomAugspurger** [comment]
https://github.com/fsspec/adlfs/pull/427/commits/78af9d177bea2408af514475bbbf67fd14fe19d6 should fix the CI failure (sync vs. async BlobPrefix)

**Comment by TomAugspurger** [comment]
Thanks!

**Comment by benrutter** [comment]
Thanks @TomAugspurger - just saw your messages now!

**Pull request merged**
